const D=window.GYM_DATA,STORE='ahmedGymV6',LIB='https://musclewiki.com/exercises';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function st(){try{return JSON.parse(localStorage.getItem(STORE))||{drafts:{},history:{}}}catch{return{drafts:{},history:{}}}}
function put(x){localStorage.setItem(STORE,JSON.stringify(x))}
function k(d,i){return d+':'+i}
function last(d){const h=st().history[d]||[];return h.length?h[h.length-1]:null}
function img(n,v){let c=null;if(n.startsWith('Machine '))c='Machine';else if(n.startsWith('Smith Machine '))c='Smith-Machine';else if(n.startsWith('Cable '))c='Cables';else if(n.startsWith('Band '))c='Band';else if(n.startsWith('Bodyweight '))c='Bodyweight';else if(n.startsWith('Dumbbell '))c='Dumbbells';else if(n.startsWith('Kettlebell '))c='Kettlebells';else if(n.includes('Stretch'))c='Stretches';if(!c)return'';const s=n.toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');return`https://media.musclewiki.com/media/uploads/og-male-${c}-${s}-${v}.jpg`}
function mw(n,u){return`<a class="mw" target="_blank" rel="noopener" href="${u||LIB}">↗ ${u?'Open in MuscleWiki':'MuscleWiki library'}</a>`}
function warm(a,t){return`<div class="box"><h3>${t}</h3>${a.map(x=>`<div class="mini"><b>${x[0]}</b><span class="dose">${x[1]}</span><p>${x[2]}</p>${mw(x[0],x[3])}</div>`).join('')}</div>`}
function hist(day){const h=(st().history[day.id]||[]).slice().reverse();if(!h.length)return'<div class="muted">No saved sessions yet.</div>';return h.map(v=>{let r=[];Object.entries(v.exercises||{}).forEach(([q,e])=>{const i=+q.split(':')[1],n=day.main[i]?.[0]||e.name||q;r.push(`<div><b>${n}</b><br>${e.sets.map((s,j)=>`S${j+1} ${s.w||'—'}×${s.r||'—'}`).join(' · ')}</div>`)});return`<div class="version"><div class="vtitle">Version ${v.version}</div><div class="vdate">${new Date(v.savedAt).toLocaleString()}</div><div class="vgrid">${r.join('')}</div></div>`}).join('')}
function ex(day,e,i){const[n,sets,reps,rest,cue,alts,url]=e,p=last(day.id)?.exercises?.[k(day.id,i)],d=(st().drafts[day.id]||{})[k(day.id,i)]||{sets:Array.from({length:sets},()=>({w:'',r:''}))};let rows='';for(let j=0;j<sets;j++){const a=d.sets[j]||{w:'',r:''},b=p?.sets?.[j];rows+=`<div class="setrow"><div class="setnum">Set ${j+1}</div><input inputmode="decimal" data-day="${day.id}" data-ex="${i}" data-set="${j}" data-f="w" value="${a.w||''}" placeholder="Weight kg"><input inputmode="numeric" data-day="${day.id}" data-ex="${i}" data-set="${j}" data-f="r" value="${a.r||''}" placeholder="Reps"><div class="prev">${b&&(b.w||b.r)?`Previous: <b>${b.w||'—'} kg × ${b.r||'—'}</b>`:'Previous: —'}</div></div>`}const f=img(n,'front'),s=img(n,'side');return`<article class="ex"><div class="top"><input class="done" type="checkbox" data-done="${day.id}:${i}"><div><div class="name">${i+1}. ${n}</div><div class="chips"><span class="chip primary">${sets} × ${reps}</span><span class="chip">Rest ${rest}</span><span class="chip">~2 RIR</span></div>${mw(n,url)}</div></div>${f?`<div class="demo"><img loading="lazy" src="${f}" onerror="this.style.display='none'"><img loading="lazy" src="${s}" onerror="this.style.display='none'"></div>`:''}<div class="body"><p><strong>Technique:</strong> ${cue}</p><div class="setlog"><div class="sethead"><span></span><span>WEIGHT</span><span>REPS</span></div>${rows}</div>${alts.length?`<details><summary>Alternatives (${alts.length})</summary>${alts.map(a=>`<div class="alt">${a[0]} ${mw(a[0],a[1])}</div>`).join('')}</details>`:''}</div></article>`}
function day(day){const h=st().history[day.id]||[],p=last(day.id),links=day.fin[2].map(a=>mw(a[0],a[1])).join(' ');return`<section id="${day.id}"><div class="focus">${day.daynum} · ${day.focus}</div><h2>${day.weekday}</h2><div class="cycle"><b>Cycle:</b> Wednesday Day 1 → Saturday Day 2 → Monday Day 3 → repeat</div><div class="session"><div class="stitle">${day.weekday} session log</div><div class="smeta">Saved versions: ${h.length}${p?` · Last: Version ${p.version} · ${new Date(p.savedAt).toLocaleDateString()}`:''}</div><div class="actions"><button class="save" onclick="save('${day.id}')">Save as new session</button><button onclick="copyPrev('${day.id}')">Copy previous weights</button><button class="clear" onclick="clearDraft('${day.id}')">Clear current draft</button></div><details><summary>View saved session history</summary>${hist(day)}</details></div>${warm(day.warm,'Warm-up · 8–11 min')}<h3>Main workout</h3>${day.main.map((e,i)=>ex(day,e,i)).join('')}<div class="box fin"><h3>CrossFit-style finisher · ${day.fin[0]}</h3><ul>${day.fin[1].map(x=>`<li>${x}</li>`).join('')}</ul>${links}</div>${warm(D.cool,'Cooldown · 4–6 min')}</section>`}
function render(){document.getElementById('app').innerHTML=D.days.map(day).join('');bind();restoreDone()}
function bind(){$$('input[data-day]').forEach(x=>x.oninput=()=>{const s=st(),d=x.dataset.day,i=+x.dataset.ex,j=+x.dataset.set,f=x.dataset.f,day=D.days.find(q=>q.id===d),cnt=day.main[i][1],q=k(d,i);s.drafts[d]=s.drafts[d]||{};s.drafts[d][q]=s.drafts[d][q]||{sets:Array.from({length:cnt},()=>({w:'',r:''}))};s.drafts[d][q].sets[j][f]=x.value;put(s)});$$('input[data-done]').forEach(x=>x.onchange=()=>localStorage.setItem(STORE+':done:'+x.dataset.done,x.checked?'1':'0'))}
function restoreDone(){$$('input[data-done]').forEach(x=>x.checked=localStorage.getItem(STORE+':done:'+x.dataset.done)==='1')}
window.save=function(id){const day=D.days.find(x=>x.id===id),s=st(),d=s.drafts[id]||{};let exercises={},has=false;day.main.forEach((e,i)=>{const q=k(id,i),a=d[q]||{sets:Array.from({length:e[1]},()=>({w:'',r:''}))},sets=a.sets.map(x=>({w:(x.w||'').trim(),r:(x.r||'').trim()}));if(sets.some(x=>x.w||x.r))has=true;exercises[q]={name:e[0],sets}});if(!has){alert('Enter at least one weight/reps value before saving.');return}s.history[id]=s.history[id]||[];const version=s.history[id].length+1;s.history[id].push({version,savedAt:new Date().toISOString(),exercises});s.drafts[id]={};put(s);day.main.forEach((e,i)=>localStorage.removeItem(STORE+':done:'+id+':'+i));render();setTimeout(()=>document.getElementById(id)?.scrollIntoView(),50);alert(`Saved as Version ${version}. Inputs are now blank for the next ${day.weekday} session.`)}
window.copyPrev=function(id){const day=D.days.find(x=>x.id===id),p=last(id);if(!p){alert('No previous session yet.');return}const s=st();s.drafts[id]={};day.main.forEach((e,i)=>{const q=k(id,i),a=p.exercises[q];s.drafts[id][q]={sets:Array.from({length:e[1]},(_,j)=>({w:a?.sets?.[j]?.w||'',r:''}))}});put(s);render();setTimeout(()=>document.getElementById(id)?.scrollIntoView(),50)}
window.clearDraft=function(id){const s=st();s.drafts[id]={};put(s);render();setTimeout(()=>document.getElementById(id)?.scrollIntoView(),50)}
render();