const DATA = window.GYM_DATA;
const STORE_KEY='ahmedGymV4:data';
const DRAFT_KEY='ahmedGymV4:draft';
let DB = loadDB();
let DRAFT = loadDraft();
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function slug(s){return s.toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function uid(){return Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,9)}
function loadDB(){try{const x=JSON.parse(localStorage.getItem(STORE_KEY)||'null');if(x&&x.sessions)return x}catch(e){} return {schema:'ahmed-gym-log-v4',createdAt:new Date().toISOString(),sessions:[]}}
function saveDB(){localStorage.setItem(STORE_KEY,JSON.stringify(DB))}
function loadDraft(){try{return JSON.parse(localStorage.getItem(DRAFT_KEY)||'{}')}catch(e){return{}}}
function saveDraft(){localStorage.setItem(DRAFT_KEY,JSON.stringify(DRAFT))}
function sourceUrl(m){if(m.source==='youtube'&&m.sourceUrl)return m.sourceUrl;if(m.source==='youtube'&&m.youtubeId)return 'https://www.youtube.com/watch?v='+m.youtubeId;return 'https://musclewiki.com/exercise/'+m.slug}
function mwImgCandidates(m,view){if(m.source!=='musclewiki')return[];const arr=[];(m.cats||[]).forEach(c=>{arr.push(`https://media.musclewiki.com/media/uploads/og-male-${c}-${m.slug}-${view}.jpg`);arr.push(`https://media.musclewiki.com/media/uploads/male-${c}-${m.slug}-${view}.jpg`)});return arr}
function installImgFallback(img,cands){let i=0;img.onerror=()=>{i++;if(i<cands.length)img.src=cands[i];else{img.onerror=null;img.src='data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="800" height="480"><rect width="100%" height="100%" fill="#0b1321"/><text x="50%" y="45%" fill="#93a4b9" text-anchor="middle" font-family="Arial" font-size="28">MuscleWiki preview unavailable</text><text x="50%" y="55%" fill="#6f839d" text-anchor="middle" font-family="Arial" font-size="19">Use the inline video below</text></svg>`)}}}
function youtubeEmbed(m){if(m.youtubeId)return 'https://www.youtube-nocookie.com/embed/'+m.youtubeId;return 'https://www.youtube.com/embed?listType=search&list='+encodeURIComponent(m.name+' exercise proper form')}
function mediaHTML(name,compact=false){const m=DATA.movements[name]||{name,source:'youtube'};const src=sourceUrl(m);let visual='';if(m.source==='youtube'&&m.youtubeId){visual=`<img class="ytthumb" src="https://img.youtube.com/vi/${m.youtubeId}/hqdefault.jpg" alt="${esc(name)}">`}else if(m.source==='musclewiki'){const fc=mwImgCandidates(m,'front'),sc=mwImgCandidates(m,'side');visual=`<div class="mwimgs"><img data-cands='${esc(JSON.stringify(fc))}' src="${fc[0]||''}" alt="${esc(name)} front"><img data-cands='${esc(JSON.stringify(sc))}' src="${sc[0]||''}" alt="${esc(name)} side"></div>`}else{visual=`<div class="mwimgs"><img class="ytthumb" src="data:image/svg+xml;charset=UTF-8,${encodeURIComponent('<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; width=&quot;800&quot; height=&quot;480&quot;><rect width=&quot;100%&quot; height=&quot;100%&quot; fill=&quot;#0b1321&quot;/><text x=&quot;50%&quot; y=&quot;50%&quot; fill=&quot;#9fb0c4&quot; text-anchor=&quot;middle&quot; font-size=&quot;28&quot; font-family=&quot;Arial&quot;>Video demo</text></svg>')}"></div>`}return `<div class="media ${compact?'mini-media':''}" data-media-for="${esc(name)}">${visual}<div class="media-actions"><a class="linkbtn" href="${src}" target="_blank" rel="noopener">↗ ${m.source==='musclewiki'?'MuscleWiki':'Source'}</a><button class="linkbtn" type="button" onclick="toggleVideo(this,'${esc(name)}')">▶ ویدیوی داخل صفحه</button></div><div class="sourcebadge">${m.source==='musclewiki'?'MuscleWiki image/page + inline video fallback':'YouTube / external video source'}${m.note?' · '+esc(m.note):''}</div><div class="video-box"><iframe loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-src="${youtubeEmbed(m)}"></iframe></div></div>`}
function hydrateImages(root=document){root.querySelectorAll('img[data-cands]').forEach(img=>{let c=[];try{c=JSON.parse(img.dataset.cands)}catch(e){}installImgFallback(img,c)})}
function toggleVideo(btn,name){const media=btn.closest('.media'),box=media.querySelector('.video-box'),fr=box.querySelector('iframe');box.classList.toggle('active');if(box.classList.contains('active')&&!fr.src)fr.src=fr.dataset.src}
function toggleSimpleMedia(btn,name){const host=btn.closest('.simple').querySelector('.simple-media');if(host.innerHTML.trim()){host.innerHTML='';return}host.innerHTML=mediaHTML(name,true);hydrateImages(host)}
function getMovement(name){return DATA.movements[name]||{name,source:'youtube'}}
function lastRecord(exerciseName){let best=null;for(const s of DB.sessions){for(const e of (s.exercises||[])){if(e.name===exerciseName){const t=new Date(s.date).getTime();if(!best||t>best.time)best={time:t,date:s.date,sets:e.sets||[],sessionId:s.id,workout:s.workoutKey}}}}return best}
function lastSummary(name){const r=lastRecord(name);if(!r)return 'هنوز رکوردی برای این حرکت ذخیره نشده.';const txt=r.sets.map((s,i)=>`S${i+1}: ${s.weight||'—'}${s.reps?' × '+s.reps:''}`).join(' · ');return `آخرین بار: <b>${txt||'—'}</b><br><span class="tiny">${new Date(r.date).toLocaleString()}</span>`}
function simpleCard(x){const alt=(x.alts||[]).map(a=>`<div class="altitem"><span>${esc(a)}</span><button class="smallbtn" onclick="previewAltSimple(this,'${esc(a)}')">نمایش media</button></div>`).join('');return `<div class="simple"><div class="simpletop"><div><b>${esc(x.name)}</b><span class="dose">${esc(x.dose)}</span></div><button class="media-toggle" onclick="toggleSimpleMedia(this,'${esc(x.name)}')">media</button></div><p>${esc(x.note||'')}</p>${alt?`<div class="altlist">${alt}</div>`:''}<div class="simple-media"></div></div>`}
function previewAltSimple(btn,name){const host=btn.closest('.simple').querySelector('.simple-media');host.innerHTML=mediaHTML(name,true);hydrateImages(host)}
function draftPath(workoutKey,slot){return `${workoutKey}:${slot}`}
function selectedName(workoutKey,slot,def){return DRAFT[draftPath(workoutKey,slot)]?.selected||def}
function exCard(w,ex,i){const path=draftPath(w.key,i),selected=selectedName(w.key,i,ex.name);const options=[ex.name,...(ex.alts||[])];const opt=options.map(n=>`<option ${n===selected?'selected':''}>${esc(n)}</option>`).join('');return `<article class="slot" data-workout="${w.key}" data-slot="${i}" data-main="${esc(ex.name)}"><div class="slothead"><div class="slotheadrow"><div class="slotnum">${i+1}</div><div style="flex:1"><h4 class="selected-title">${esc(selected)}</h4><div class="chips"><span class="chip main">${ex.sets} × ${esc(ex.reps)}</span><span class="chip">Rest ${esc(ex.rest)}</span><span class="chip">${esc(ex.rir)} RIR</span></div><select class="selector" onchange="switchExercise(this)">${opt}</select></div></div></div><div class="mediahost">${mediaHTML(selected)}</div><div class="slotbody"><div class="cue"><strong>Technique:</strong> ${esc(ex.cue)}</div><div class="lastsummary">${lastSummary(selected)}</div><div class="setgrid">${setRows(w,ex,i,selected)}</div><div class="slottools"><button class="smallbtn" onclick="copyLastWeights(this)">Copy last weights</button><button class="smallbtn" onclick="clearSlot(this)">Clear this exercise</button></div>${(ex.alts||[]).length?`<div class="altlist"><b class="tiny">Alternatives — هرکدام media مستقل دارند:</b>${ex.alts.map(a=>`<div class="altitem"><span>${esc(a)}</span><button class="smallbtn" onclick="selectAlt(this,'${esc(a)}')">انتخاب + نمایش</button></div>`).join('')}</div>`:''}</div></article>`}
function setRows(w,ex,i,name){const path=draftPath(w.key,i),d=DRAFT[path]||{},latest=lastRecord(name);let h='';for(let s=0;s<ex.sets;s++){const cur=d.sets?.[s]||{},p=latest?.sets?.[s]||{};h+=`<div class="setrow"><div class="setno">Set ${s+1}</div><div class="cell"><label>Weight / level</label><input inputmode="decimal" data-kind="weight" data-set="${s}" value="${esc(cur.weight||'')}" oninput="draftInput(this)"></div><div class="cell"><label>Reps</label><input inputmode="numeric" data-kind="reps" data-set="${s}" value="${esc(cur.reps||'')}" oninput="draftInput(this)"></div><div class="prev">Previous: <b>${esc(p.weight||'—')}${p.reps?' × '+esc(p.reps):''}</b></div></div>`}return h}
function dayHTML(w){return `<section class="day" id="${w.key}"><div class="daytitle"><div class="tag">WEEK ${w.week} · ${w.day}</div><h3>${esc(w.title)}</h3></div><div class="sectiontitle">Warm-up</div>${w.warm.map(simpleCard).join('')}<div class="sectiontitle">Main workout</div>${w.main.map((x,i)=>exCard(w,x,i)).join('')}<div class="sectiontitle">Conditioning / Finisher</div>${w.finisher.map(simpleCard).join('')}<div class="sectiontitle">Cooldown</div>${w.cool.map(simpleCard).join('')}<div class="sessionbar"><div class="row"><button class="btn primary" onclick="saveSession('${w.key}',this)">Save session + JSON</button><button class="btn" onclick="newSession('${w.key}',this)">Start new session</button><button class="btn gold" onclick="showHistory('${w.key}',this)">History</button></div><div class="status"></div><div class="history"></div></div></section>`}
function render(){const nav=document.getElementById('nav');nav.innerHTML=DATA.plan.map(w=>`<button onclick="location.hash='${w.key}'">${w.week}${w.day==='Wednesday'?'·Wed':w.day==='Saturday'?'·Sat':'·Mon'}</button>`).join('');const A=DATA.plan.filter(x=>x.week==='A'),B=DATA.plan.filter(x=>x.week==='B');document.getElementById('app').innerHTML=`<div class="week"><div class="weekhead"><div><h2>Week A</h2><p>هسته اصلی + baseline</p></div></div>${A.map(dayHTML).join('')}</div><div class="week"><div class="weekhead"><div><h2>Week B</h2><p>همان هسته؛ فقط accessoryهای محدود rotate می‌شوند.</p></div></div>${B.map(dayHTML).join('')}</div>`;hydrateImages()}
function switchExercise(sel){const card=sel.closest('.slot'),wkey=card.dataset.workout,slot=card.dataset.slot,exName=sel.value,w=DATA.plan.find(x=>x.key===wkey),ex=w.main[slot];const path=draftPath(wkey,slot),old=DRAFT[path]||{};DRAFT[path]={selected:exName,sets:old.selected===exName?(old.sets||[]):[]};saveDraft();card.querySelector('.selected-title').textContent=exName;card.querySelector('.mediahost').innerHTML=mediaHTML(exName);hydrateImages(card.querySelector('.mediahost'));card.querySelector('.lastsummary').innerHTML=lastSummary(exName);card.querySelector('.setgrid').innerHTML=setRows(w,ex,slot,exName)}
function selectAlt(btn,name){const card=btn.closest('.slot'),sel=card.querySelector('.selector');sel.value=name;switchExercise(sel);card.scrollIntoView({behavior:'smooth',block:'start'})}
function draftInput(inp){const card=inp.closest('.slot'),wkey=card.dataset.workout,slot=card.dataset.slot,path=draftPath(wkey,slot);const exName=card.querySelector('.selector').value;DRAFT[path]=DRAFT[path]||{selected:exName,sets:[]};DRAFT[path].selected=exName;const s=+inp.dataset.set;DRAFT[path].sets[s]=DRAFT[path].sets[s]||{weight:'',reps:''};DRAFT[path].sets[s][inp.dataset.kind]=inp.value;saveDraft()}
function clearSlot(btn){const card=btn.closest('.slot'),wkey=card.dataset.workout,slot=card.dataset.slot,path=draftPath(wkey,slot),sel=card.querySelector('.selector').value;DRAFT[path]={selected:sel,sets:[]};saveDraft();card.querySelectorAll('input').forEach(x=>x.value='')}
function copyLastWeights(btn){const card=btn.closest('.slot'),name=card.querySelector('.selector').value,r=lastRecord(name);if(!r)return alert('رکورد قبلی برای این حرکت نداریم.');const inputs=card.querySelectorAll('input[data-kind="weight"]');inputs.forEach((x,i)=>{x.value=r.sets?.[i]?.weight||'';draftInput(x)});card.querySelectorAll('input[data-kind="reps"]').forEach(x=>{x.value='';draftInput(x)})}
function collectWorkout(wkey){const w=DATA.plan.find(x=>x.key===wkey),exercises=[];document.querySelectorAll(`.slot[data-workout="${wkey}"]`).forEach(card=>{const name=card.querySelector('.selector').value,sets=[];card.querySelectorAll('.setrow').forEach(row=>{sets.push({weight:row.querySelector('[data-kind="weight"]').value.trim(),reps:row.querySelector('[data-kind="reps"]').value.trim()})});exercises.push({name,sets})});return{id:uid(),date:new Date().toISOString(),workoutKey:wkey,week:w.week,day:w.day,title:w.title,exercises}}
function saveSession(wkey,btn){const s=collectWorkout(wkey);const any=s.exercises.some(e=>e.sets.some(x=>x.weight||x.reps));if(!any&&!confirm('هیچ وزن/تکراری وارد نشده. همین جلسه خالی ذخیره شود؟'))return;DB.sessions.push(s);saveDB();const box=btn.closest('.sessionbar');box.querySelector('.status').textContent='✓ جلسه ذخیره شد؛ JSON کامل هم دانلود شد.';exportJSON(true);refreshWorkout(wkey)}
function refreshWorkout(wkey){document.querySelectorAll(`.slot[data-workout="${wkey}"]`).forEach(card=>{const name=card.querySelector('.selector').value;card.querySelector('.lastsummary').innerHTML=lastSummary(name);card.querySelectorAll('.setrow').forEach((row,i)=>{const p=lastRecord(name)?.sets?.[i]||{};row.querySelector('.prev b').textContent=(p.weight||'—')+(p.reps?' × '+p.reps:'')})})}
function newSession(wkey,btn){document.querySelectorAll(`.slot[data-workout="${wkey}"]`).forEach(card=>{const slot=card.dataset.slot,path=draftPath(wkey,slot),sel=card.querySelector('.selector').value;DRAFT[path]={selected:sel,sets:[]};card.querySelectorAll('input').forEach(x=>x.value='')});saveDraft();btn.closest('.sessionbar').querySelector('.status').textContent='جلسه جدید آماده است؛ Previousها حفظ شده‌اند.'}
function exportJSON(auto=false){const payload={schema:'ahmed-gym-log-v4',exportedAt:new Date().toISOString(),plan:'14-Day Hybrid Hypertrophy + Health',sessions:DB.sessions};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');const d=new Date(),pad=n=>String(n).padStart(2,'0');a.href=URL.createObjectURL(blob);a.download=`ahmed-gym-log-${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}_${pad(d.getHours())}-${pad(d.getMinutes())}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);if(!auto)document.getElementById('globalStatus').textContent='JSON backup downloaded.'}
function mergeImported(obj){if(!obj||!Array.isArray(obj.sessions))throw new Error('این فایل ساختار sessions معتبر ندارد.');const map=new Map(DB.sessions.map(s=>[s.id,s]));for(const s of obj.sessions){if(s&&s.id)map.set(s.id,s)}DB.sessions=[...map.values()].sort((a,b)=>new Date(a.date)-new Date(b.date));saveDB()}
document.getElementById('importFile').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const obj=JSON.parse(await f.text());mergeImported(obj);document.getElementById('globalStatus').textContent=`✓ Import شد. کل جلسات ذخیره‌شده: ${DB.sessions.length}`;render()}catch(err){document.getElementById('globalStatus').textContent='Import error: '+err.message}e.target.value=''});
function showHistory(wkey,btn){const host=btn.closest('.sessionbar').querySelector('.history');if(host.innerHTML){host.innerHTML='';return}const h=DB.sessions.filter(s=>s.workoutKey===wkey).sort((a,b)=>new Date(b.date)-new Date(a.date));host.innerHTML=h.length?`<details open><summary>${h.length} saved version(s)</summary>${h.map((s,i)=>`<div class="histrow"><b>Version ${h.length-i}</b> · ${new Date(s.date).toLocaleString()}<br>${s.exercises.map(e=>`${esc(e.name)}: ${e.sets.map(x=>(x.weight||'—')+(x.reps?'×'+x.reps:'')).join(', ')}`).join('<br>')}</div>`).join('')}</details>`:'<div class="tiny">هنوز نسخه‌ای ذخیره نشده.</div>'}
render();